force-app/main/default/objects/Account__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Error_Logs__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logs__c/fields/Run_By__c.field-meta.xml
<CustomField>
    <fullName>Run_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Run By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Incoming_Webhooks__c/Incoming_Webhooks__c.object-meta.xml
<CustomObject>
    <label>inwise Incoming Webhooks</label>
    <nameField>
        <displayFormat>IW-{0000}</displayFormat>
        <label>Incoming Webhooks Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>inwise Incoming Webhooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Landing_Sync__c/Landing_Sync__c.object-meta.xml
<CustomObject>
    <label>inwise Landing Sync</label>
    <nameField>
        <label>Sync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inwise Landing Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Landing_Sync__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inwise Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>inwise Landing Sync</relationshipLabel>
    <relationshipName>inwise_Landing_Sync</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Landing_Sync_History__c/fields/Landing_Sync__c.field-meta.xml
<CustomField>
    <fullName>Landing_Sync__c</fullName>
    <label>inwise Landing Sync</label>
    <referenceTo>Landing_Sync__c</referenceTo>
    <relationshipLabel>inwise Landing Sync History</relationshipLabel>
    <relationshipName>inwise_Landing_Sync_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Landing_Sync_History__c/fields/Run_By__c.field-meta.xml
<CustomField>
    <fullName>Run_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Run By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inwise_Landing_Sync_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Run_By__c.field-meta.xml
<CustomField>
    <fullName>Run_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Run By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>inwise_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Run_On__c.field-meta.xml
<CustomField>
    <fullName>Run_On__c</fullName>
    <label>Run On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Settings__c/fields/Landing_Sync_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Landing_Sync_Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Landing Sync Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InwiseSettingsControllerTest.cls
/******************************************************************************************
*Created By:  Kapil Goutam
*Created On: 
*Purpose :  Test class for inwiseSettingController
* * -----------------------------------------------------
* Modified On       Modified By     Purpose
* 05/29/2019        Kapil Goutam    code coverage
/******************************************************************************************/

@isTest
public class InwiseSettingsControllerTest {
    
    @isTest 
    static void settingsTest() {

        Token_Setting__c tokenSetting = inwiseTestDataFactory.GetInwiseTokenSetting();
        insert tokenSetting;  
        
        Account__c act1 = inwiseTestDataFactory.GetInwiseAccount();
        act1.Default__c = true;
        insert act1;

        tokenSetting.Account_Id__c = act1.Id;
        update tokenSetting;  
        
        Settings__c s = new Settings__c();
        s.name = 'default';
        s.Landing_Sync_Scheduled__c = true;
        insert s;
        
        Error_Logs__c objErrorLog = new Error_Logs__c();
        objErrorLog.Message__c = 'POST_Test';
        objErrorLog.Run_On__c = datetime.now();
        objErrorLog.Class_Name__c = 'TestClass';
        objErrorLog.Method_Name__c = 'TestMethod';
        objErrorLog.Run_By__c = UserInfo.getUserId();
        insert objErrorLog; 
        
        Landing_Sync__c landingSync = new Landing_Sync__c();
        landingSync.Name = 'hello test';
        landingSync.Record_Index__c = 23;
        landingSync.Last_JobId__c = 'hhw';
        landingSync.Landing_Page_Id__c = 22;
        landingSync.Last_JobName__c = 'test 2';
        landingSync.Landing_Page_Name__c = 'test landing';
        insert landingSync;
        
        Test.startTest();
        
        Test.setCurrentPage(Page.inwiseSettings);
        inwiseSettingsController controller = new inwiseSettingsController(new ApexPages.StandardController(act1));
        controller.doReturnCustomSettingUrl();
        Pagereference pagref1 = controller.redirectToListView('Logs__c');
        Pagereference pageref2 = controller.doReturnLogsUrl();
        System.assertEquals(pagref1.geturl(), pageref2.geturl());
        
        Pagereference pagref11 = controller.redirectToListView('Sync_Master__c');
        Pagereference pageref3 = controller.doReturnSyncMasterUrl();
        System.assertEquals(pagref11.geturl(), pageref3.geturl());
        
        System.debug(controller.currentPackageVersion);
        System.debug(controller.turnOnOffTrackLogBtnLabel);
        System.debug(controller.turnOnOffErrorLogBtnLabel);
        System.debug(controller.turnOnOffLandingSyncBtnLabel);
        System.debug(controller.turnOnOffCampaignSyncBtnLabel);
        System.debug(controller.turnOnOffTrackActivityBtnLabel);
        
        Pagereference pagref4 = controller.redirectToListView('Landing_Sync_History__c');
        Pagereference pageref5 = controller.doReturnLandingSyncHistoryUrl();
        System.assertEquals(pagref4.geturl(), pageref5.geturl());
        
        Pagereference pagref6 = controller.redirectToListView('Incoming_Webhooks__c');
        Pagereference pageref7 = controller.doReturnIncomingWebhooksUrl();
        System.assertEquals(pagref6.geturl(), pageref7.geturl());
        
        controller.doClearLogs();
        controller.doClearIncomingWebhooks();
        controller.doSendLogtoinwiseSupport(); 
        controller.doSendErrorLogtoinwiseSupport();
        controller.turnOnOffCampaignSync();
        controller.objInwiseUtil = new InwiseUtil(null);
        controller.turnOnOffCampaignSync();
        controller.doInboundSMSConfiguration();
        controller.toggleSettingLandingSync();
        controller.turnOnOffLandingSync();
        controller.turnOnOffLandingSync();
        controller.objinwiseLtngConstants.isLightning = true;
        controller.doReturnLogsUrl();
        controller.doCheckAndCreateRemoteSite();
        controller.doClearErrorLogs();
        controller.doReturnErrorLogsUrl();
        controller.doClearLandingSync();
        controller.turnOnOffTrackLog(); 
        controller.turnOnOffTrackError();
        controller.turnOnOffTrackActivities();
        Test.stopTest();
    }
}