force-app/main/default/objects/Account__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Landing_Sync__c/Landing_Sync__c.object-meta.xml
<CustomObject>
    <label>inwise Landing Sync</label>
    <nameField>
        <label>Sync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inwise Landing Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Landing_Sync__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inwise Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>inwise Landing Sync</relationshipLabel>
    <relationshipName>inwise_Landing_Sync</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Landing_Sync__c/fields/Leads__c.field-meta.xml
<CustomField>
    <fullName>Leads__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leads</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Landing_Sync__c/fields/Scheduled_Daily_At__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Daily_At__c</fullName>
    <label>Scheduled Daily At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
            <value>
                <fullName>1:00 AM</fullName>
            </value>
            <value>
                <fullName>2:00 AM</fullName>
            </value>
            <value>
                <fullName>3:00 AM</fullName>
            </value>
            <value>
                <fullName>4:00 AM</fullName>
            </value>
            <value>
                <fullName>5:00 AM</fullName>
            </value>
            <value>
                <fullName>6:00 AM</fullName>
            </value>
            <value>
                <fullName>7:00 AM</fullName>
            </value>
            <value>
                <fullName>8:00 AM</fullName>
            </value>
            <value>
                <fullName>9:00 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>12:00 PM</fullName>
            </value>
            <value>
                <fullName>1:00 PM</fullName>
            </value>
            <value>
                <fullName>2:00 PM</fullName>
            </value>
            <value>
                <fullName>3:00 PM</fullName>
            </value>
            <value>
                <fullName>4:00 PM</fullName>
            </value>
            <value>
                <fullName>5:00 PM</fullName>
            </value>
            <value>
                <fullName>6:00 PM</fullName>
            </value>
            <value>
                <fullName>7:00 PM</fullName>
            </value>
            <value>
                <fullName>8:00 PM</fullName>
            </value>
            <value>
                <fullName>9:00 PM</fullName>
            </value>
            <value>
                <fullName>10:00 PM</fullName>
            </value>
            <value>
                <fullName>11:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Landing_Sync_Mapping__c/fields/Landing_Sync__c.field-meta.xml
<CustomField>
    <fullName>Landing_Sync__c</fullName>
    <label>inwise Landing Sync</label>
    <referenceTo>Landing_Sync__c</referenceTo>
    <relationshipLabel>inwise Landing Sync Mapping</relationshipLabel>
    <relationshipName>inwise_Landing_Sync_Mapping</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/inwiseLandingSyncScheduleJobCtrlTest.cls
/******************************************************************************************
*Created By:  Kapil Goutam
*Created On: 02/02/2017
*Purpose :     test class for inwiseLandingSyncScheduleJobController
*Modified:   
/******************************************************************************************/
@isTest
private class inwiseLandingSyncScheduleJobCtrlTest {
     static testmethod void inwiseLandingSyncScheduleJobController_test1() {
        // Implement test code
          Settings__c objSetting = inwiseTestDataFactory.GetInwiseSetting();
          insert objSetting;

          Token_Setting__c tokenSetting = inwiseTestDataFactory.GetInwiseTokenSetting();
          insert tokenSetting;  

          Account__c act1 = inwiseTestDataFactory.GetInwiseAccount();
          act1.Default__c = true;
          insert act1;  
          
          tokenSetting.Account_Id__c = act1.Id;
          update tokenSetting;  
        
          lead objLead = new Lead(lastname='inwise Landing Sync',company='company',status='Open - Not Contacted');
          insert objLead; 
          Test.setCurrentPage(Page.inwiseLandingSyncScheduleJob);
          
          Landing_Sync__c objLandingSync = new Landing_Sync__c();
          objLandingSync.Name = 'Test Landing Sync';
          objLandingSync.Leads__c = true;
          objLandingSync.Landing_Page_Id__c=null;
          //objLandingSync.Landing_Page_Name__c = 'Landing Page1';
          insert objLandingSync;
          ApexPages.currentPage().getParameters().put('retUrl','/apex/inwisehome');
          ApexPages.currentPage().getParameters().put('id',objLandingSync.Id);

          // Test execution start

          test.startTest();
    

          inwiseLandingSyncScheduleJobController obj  = new inwiseLandingSyncScheduleJobController();
          String s =  inwiseLandingSyncScheduleJobController.getCronExpression('12:00 AM');
          System.assertEquals(s,'0 0 0 1/1 * ? *');
          String s1 = inwiseLandingSyncScheduleJobController.getCronExpressionTemp('12:00 AM');
          system.assertNotEquals(s1,'0 11 14 2 12 ? 2017');

          /*******************************************************************************************************************************************************************************
          Page is NOT in use because individual schedule functionality do not work now for LANDING SYNC ------As per input by Boaz - 17 Aug 2017 ---
          ********************************************************************************************************************************************************************************
          pageReference  url1 = obj.gotoHome();
          pageReference  url2 = new pageReference('/apex/inwisehome');
          System.assertEquals(url1.getUrl(),url2.getUrl());             
          obj.doSchedule();
          obj.objSync.Scheduled_Daily_At__c = '12:00 AM';
           obj.doSchedule();
         // obj2.doScheduleNow();
          obj.objSync.Scheduled_Daily_At__c = '12:00 PM';
          obj.doSchedule();
          obj.objSync.Scheduled_Daily_At__c = '10:00 AM';
          obj.doSchedule();
          obj.objSync.Scheduled_Daily_At__c = '10:00 PM';
          obj.objSync.Landing_page_Id__c = 5341;
          obj.doSchedule();
          List<Landing_Sync_Mapping__c> objMappingList = new List<Landing_Sync_Mapping__c>();
          objMappingList.add(new Landing_Sync_Mapping__c(inwise_Field__c = 'Name', inwise_FieldId__c = 'inwise Landing Sync', Landing_Sync__c = obj.objSync.Id , Salesforce_Field__c='LastName'));
          insert objMappingList ;
          obj.doSchedule();
            List<Apexpages.Message> pageMessages = ApexPages.getMessages();
           System.assertEquals(pageMessages[0].getDetail(),'Please select time to schedule a Sync.');   
           System.assertEquals(pageMessages[1].getDetail(),'Scheduled, Please go to home page to see the progress.');       
          // test execution ends
          ****/
          test.stopTest();
    }
     static testmethod void inwiseLandingSyncScheduleJobController_test3(){
        Settings__c objSetting = inwiseTestDataFactory.GetInwiseSetting();
        insert objSetting;

        Token_Setting__c tokenSetting = inwiseTestDataFactory.GetInwiseTokenSetting();
        insert tokenSetting;  

        Account__c act1 = inwiseTestDataFactory.GetInwiseAccount();
        act1.Default__c = true;
        insert act1;     

        tokenSetting.Account_Id__c = act1.Id;
        update tokenSetting;  
      
        lead objLead = new Lead(lastname='inwise Landing Sync',company='company',status='Open - Not Contacted');
        insert objLead; 
        Test.setCurrentPage(Page.inwiseLandingSyncScheduleJob);
        
        Landing_Sync__c objLandingSync = new Landing_Sync__c();
        objLandingSync.Name = 'Test Landing Sync';
        objLandingSync.Leads__c = true;
        objLandingSync.Landing_Page_Id__c=null;
        //objLandingSync.Landing_Page_Name__c = 'Landing Page1';
        insert objLandingSync;
        ApexPages.currentPage().getParameters().put('retUrl','/apex/inwisehome');
        ApexPages.currentPage().getParameters().put('id',objLandingSync.Id);

        // Test execution start

        test.startTest();
       String s =  inwiseLandingSyncScheduleJobController.getCronExpression('12:00 PM');
       System.assertEquals(s,'0 0 12 1/1 * ? *');
        test.stopTest();

     }
   /*******************************************************************************************************************************************************************************
    Page is NOT in use because individual schedule functionality do not work now for LANDING SYNC ------As per input by Boaz - 17 Aug 2017 ---
    ********************************************************************************************************************************************************************************
     static testmethod void inwiseLandingSyncScheduleJobController_test2() {
        // Implement test code
          Settings__c objSetting = inwiseTestDataFactory.GetInwiseSetting();
          insert objSetting;

          lead objLead = new Lead(lastname='inwise Landing Sync',company='company',status='Open - Not Contacted');
          insert objLead; 
          Test.setCurrentPage(Page.inwiseLandingSyncScheduleJob);
          
          Landing_Sync__c objLandingSync = new Landing_Sync__c();
          objLandingSync.Name = 'Test Landing Sync';
          objLandingSync.Leads__c = true;
          objLandingSync.Landing_Page_Id__c=null;
          //objLandingSync.Landing_Page_Name__c = 'Landing Page1';
          insert objLandingSync;
          ApexPages.currentPage().getParameters().put('retUrl','/apex/inwisehome');
          ApexPages.currentPage().getParameters().put('id',objLandingSync.Id);

          // Test execution start

          test.startTest();
          inwiseLandingSyncScheduleJobController obj = new inwiseLandingSyncScheduleJobController();
          obj = new inwiseLandingSyncScheduleJobController();
           obj.doScheduleNow();
           List<Apexpages.Message> pageMessages = ApexPages.getMessages();
           System.assertEquals(pageMessages[0].getDetail(),'Start executing now, please go to home page to see the progress.');
          // test execution ends
          test.stopTest();
    }    
    ************/
}