force-app/main/default/objects/Account__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password (deprecate)</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/inwiseRegistrationControllerTest.cls
/******************************************************************************************
*Created By:  Kapil Goutam
*Created On:  5th April 2017
*Purpose :    code coverage  inwiseRegistrationController
/******************************************************************************************/
@isTest
private class inwiseRegistrationControllerTest {
    
    //@isTest static void test_method_one() {
        /*PageReference pageRef = Page.inwiseRegistration;
        Test.setCurrentPage(pageRef);
        Account__c objAccount = new Account__c();
        objAccount.Name = 'Test Act';
        insert objAccount;
        ApexPages.StandardController stdController =  new ApexPages.StandardController(objAccount);
        inwiseRegistrationController  objIwiseController = new inwiseRegistrationController (stdController);
        objIwiseController.getStarted();
        List<Apexpages.Message> msgs = ApexPages.getMessages();
        System.assertEquals(msgs.size(),1);
        System.assertEquals(msgs[0].getDetail(),'Please fill all fields for registration');
        objIwiseController.companyName = 'inwise Account 1';
        objIwiseController.contactName = 'inwiseTestContact';
        objIwiseController.phone = '0123456789';
        objIwiseController.email = 'testinwise@testinwise.com';
        objIwiseController.getStarted();
        msgs = ApexPages.getMessages();
        System.assertEquals(msgs.size(),1);
        System.assertEquals(msgs[0].getDetail(),'Please fill all fields for registration');
        //System.assertEquals(msgs[1].getDetail(),'You successfully created an account!');
        //objAccount = [select id,name,User_Name__c,Password__c from Account__c where User_Name__c =:objIwiseController.email limit 1];
        //System.assertEquals(objAccount.Name,objIwiseController.contactName);
        //System.assertEquals(objAccount.User_Name__c,objIwiseController.email);
        //System.assertEquals(objAccount.Password__c,objIwiseController.contactPassword);
        objIwiseController.gotoHome();*/
    //}	
}