force-app/main/default/objects/Landing_Sync__c/Landing_Sync__c.object-meta.xml
<CustomObject>
    <label>inwise Landing Sync</label>
    <nameField>
        <label>Sync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>inwise Landing Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Landing_Sync__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>inwise Account</label>
    <referenceTo>Account__c</referenceTo>
    <relationshipLabel>inwise Landing Sync</relationshipLabel>
    <relationshipName>inwise_Landing_Sync</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InwiseLandingSyncTriggerHandler.cls
/******************************************************************************************
* Created By	: 	Shyam Vaishnav
* Created On	: 	22 Aug 2022
* Purpose 		:   Handler class of inwiseLandingSyncTrigger trigger
/******************************************************************************************
Modification Log
----------------
Date              Version   Developer                  Comments
------------------------------------------------------------------------------------
08/22/2022        1.0.0     Shyam Vaishnav             Created
/***********************************************************************************/
public with sharing class InwiseLandingSyncTriggerHandler {
    
    public static void afterDelete(List<Landing_Sync__c> listOldLandingSync){
        
        Map<String, String> automationIdMap = new Map<String, String>();
        if(Schema.sObjectType.Landing_Sync__c.isAccessible() && Schema.sObjectType.Landing_Sync__c.fields.Automation_Id__c.isAccessible()){
            for(Landing_Sync__c oldLandingSync : listOldLandingSync){
                if(String.isNotBlank(oldLandingSync.Automation_Id__c) && String.isNotBlank(oldLandingSync.Account__c)){
                    automationIdMap.put(oldLandingSync.Automation_Id__c, oldLandingSync.Account__c);
                }
            }
        }    
        
        if(!automationIdMap.isEmpty()){
            Database.executeBatch(new BatchDeleteInwiseAutomation(automationIdMap), 1);
        }
    }
}