force-app/main/default/objects/Incoming_Webhooks__c/Incoming_Webhooks__c.object-meta.xml
<CustomObject>
    <label>inwise Incoming Webhooks</label>
    <nameField>
        <displayFormat>IW-{0000}</displayFormat>
        <label>Incoming Webhooks Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>inwise Incoming Webhooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incoming_Webhooks__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>inwise_Incoming_Webhooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RestAPIIncomingWebhooksTest.cls
/******************************************************************************************
*Created By:  Kapil Goutam
*Created On: 04-April-2020
*Purpose :  test class for RestAPIIncomingWebhooks
******************************************************************************************/
@isTest
Public class RestAPIIncomingWebhooksTest{

    static testMethod void testDoPost(){

        contact con = new contact();
        con.LastName = 'test contact';
        insert  con;

        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
    
        req.requestURI = '/services/apexrest/IncomingWebhooks'; 
        req.addParameter('triggerType','clicked on link' );
        req.addParameter('timeStamp','2020-03-10 12:48:56' );
        req.addParameter('channelType', 'Email');
        req.addParameter('campaign_id','787963' );
        req.addParameter('group_id', '787963');
        req.addParameter('ip', '84.228.153.2');
        req.addParameter('remarks', '787963');
        req.addParameter('contact[external_id]', con.Id);
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();
        RestAPIIncomingWebhooks.ApiService();
        Test.stopTest();

        List<Incoming_Webhooks__c> incomingWebhookList = [Select Id,Contact__c From Incoming_Webhooks__c];
        System.assertEquals(1, incomingWebhookList.size());
        System.assertEquals(con.Id, incomingWebhookList[0].Contact__c);
    }

    static testMethod void testDoPost1(){

        contact con = new contact();
        con.LastName ='test contact';
        insert  con;

        Campaign camp = new Campaign(Name = 'Test', IsActive = TRUE);
        insert camp;

        CampaignMember member = new CampaignMember(ContactId = con.Id, Status = 'sent', CampaignId = camp.Id); 
        insert member; 
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
    
        req.requestURI = '/services/apexrest/IncomingWebhooks'; 
        req.addParameter('triggerType','clicked on link' );
        req.addParameter('timeStamp','2020-03-10 12:48:56' );
        req.addParameter('channelType', 'Email');
        req.addParameter('campaign_id','787963' );
        req.addParameter('group_id', '787963');
        req.addParameter('ip', '84.228.153.2');
        req.addParameter('remarks', '787963');
        req.addParameter('contact[external_id]', member.Id);
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();
        RestAPIIncomingWebhooks.ApiService();
        Test.stopTest();

        List<Incoming_Webhooks__c> incomingWebhookList = [Select Id,Contact__c From Incoming_Webhooks__c];
        System.assertEquals(1, incomingWebhookList.size());
        System.assertEquals(con.Id, incomingWebhookList[0].Contact__c);
    }     
}