force-app/main/default/objects/Sync__c/fields/Contacts__c.field-meta.xml
<CustomField>
    <fullName>Contacts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contacts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sync__c/fields/Contacts_SOQL__c.field-meta.xml
<CustomField>
    <fullName>Contacts_SOQL__c</fullName>
    <label>Contacts SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sync__c/fields/Leads__c.field-meta.xml
<CustomField>
    <fullName>Leads__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Leads</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sync__c/fields/Leads_SOQL__c.field-meta.xml
<CustomField>
    <fullName>Leads_SOQL__c</fullName>
    <label>Leads SOQL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/inwiseQueryControllerTest.cls
/******************************************************************************************
*Created By:  Kapil Goutam
*Created On: 
*Purpose :     Code coverage for inwiseQueryController class
/******************************************************************************************/
@isTest
private class inwiseQueryControllerTest {
        static testMethod void inwiseQueryControllerTest_Lead(){
                Sync__c objSync = new Sync__c();
                objSync.name = 'leadSync';
                objSync.Group_Name__c = 'campaign5';
                insert objSync;
                lead objLead = new Lead(firstname='lead',lastname='1',company='company');
                insert objLead;
                objSync.Leads__c = true;
                objSync.Leads_SOQL__c = 'SELECT ID,Name from Lead';
                update objSync;
                Test.setCurrentPage(Page.inwiseQuery);
                ApexPages.currentPage().getParameters().put('id', objSync.Id);
                inwiseQueryController objinwiseQueryController = new inwiseQueryController();
                System.assertEquals(objinwiseQueryController.listOfLeads.size(),objinwiseQueryController.listOfLeads.size());
                objinwiseQueryController.gotoHome();
        }  
        static testMethod void inwiseQueryControllerTest_Contact(){
                Sync__c objSync = new Sync__c();
                objSync.name = 'contactSync';
                objSync.Group_Name__c = 'campaign5';
                insert objSync;
                contact objContact = new contact(firstname='lead',lastname='1');
                insert objContact;
                objSync.Contacts__c = true;
                objSync.Contacts_SOQL__c = 'SELECT ID,Name from Contact';
                update objSync;
                Test.setCurrentPage(Page.inwiseQuery);
                ApexPages.currentPage().getParameters().put('id', objSync.Id);
                inwiseQueryController objinwiseQueryController = new inwiseQueryController();
                System.assertEquals(objinwiseQueryController.listOfContacts.size(),objinwiseQueryController.listOfContacts.size());
                objinwiseQueryController.gotoSchedule();
        }        
}